name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Run linter
        run: |
          make lint
