name: Node CI

on:
  - push

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Run linter
        run: |
          make lint
  
   
